controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_detail:
    path: '/product/{id}'
    controller: 'App\Controller\ProductController::show'
    requirements:
        id: '\d+'

dashboard:
    path: /
    controller: 'App\Controller\HomeController::index'

product_list:
    path: /products
    controller: 'App\Controller\ProductController::index'

customer_list:
    path: /customers
    controller: 'App\Controller\CustomerController::index'

